swarm-clients:
  image: "jenkinsci/jnlp-slave"
  user: "${user}"
  labels:
    io.rancher.scheduler.affinity:host_label_soft: ci=worker
    io.rancher.container.hostname_override: container_name
  environment:
    JENKINS_URL: "${jenkins_url}"
    JENKINS_SECRET: "${jenkins_secret}"
    SWARM_EXECUTORS: "${swarm_executors}"
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/bin/docker:/usr/bin/docker'
