swarm-clients:
  image: "jenkinsci/jnlp-slave"
  user: "${user}"
  labels:
    io.rancher.scheduler.affinity:host_label_soft: profile=infrastructure
    io.rancher.container.hostname_override: container_name
  environment:
    JENKINS_URL: "${jenkins_url}"
    JENKINS_SECRET: "${jenkins_secret}"
    JENKINS_AGENT_NAME: "${agent_name}"
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/bin/docker:/usr/bin/docker'
    - '/tmp:/tmp'
