.catalog:
  name: Jenkins Swarm
  version: "2.0-rancher1"
  description: |
    Containers that run the slave plugin.
  questions:
    - variable: jenkins_url
      label: "Jenkins Server URL e.g. http://host:port"
      type: "string"
      required: true
      description: |
        Jenkins server URL
    - variable: jenkins_secret
      label: "Jenkins API key"
      type: "string"
      required: true
      description: |
        Username to authenticate to a secured Jenkins host with.
    - variable: agent_name
      label: "Name agent should register itself as"
      type: "string"
      required: true
      description: |
        Jenkins server URL
    - variable: user
      label: "User to run swarm process"
      description: |
        If using the Host Docker, this needs to be root.
      default: jenkins
      required: true
      type: enum
      options:
        - jenkins
        - root
