.catalog:
  name: Jenkins Swarm
  version: "2.0-rancher1"
  description: |
    Containers that run the slave plugin.
  questions:
    - variable: user
      label: "User to run swarm process"
      description: |
        If using the Host Docker, this needs to be root.
      default: jenkins
      required: true
      type: enum
      options:
        - jenkins
        - root
    - variable: jenkins_secret
      label: "Jenkins secret"
      type: "string"
      required: true
      description: |
        Username to authenticate to a secured Jenkins host with.
    - variable: swarm_executors
      required: false
      type: "string"
      description: |
        Number of executors on the swarm. Default is #cpus
    - variable: jenkins_url
      label: "Jenkins Server URL"
      type: "string"
      required: true
      description: |
        Jenkins server URL
